language: node_js

node_js:
  - '8'
  - '10'
  - '11'
  - '12'
  - '13'

os:
  - linux
  - osx
  - windows

matrix:
  fast_finish: true

cache:
  directories:
    - ${HOME}/.npm

before_install:
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then  npm install --global npm@latest ; fi

before_script:
  - git config --global user.name 'CI'
  - git config --global user.email 'dummy@example.org'

script:
  - npm test

after_script:
  - nyc report --reporter=text-lcov | coveralls
