language: node_js

node_js:
  - '8'
  - '10'
  - '12'
  
os:
  - windows
  - linux
  - osx

matrix:
  fast_finish: true

cache:
  directories:
    - ${HOME}/.npm

before_script:
  - git config --global user.name 'CI'
  - git config --global user.email 'dummy@example.org'

script:
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then npm run test-windows ; else npm test ; fi

after_script:
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then nyc report --reporter=text-lcov | coveralls ; fi
  
