environment:
  matrix:
    - nodejs_version: 6
    - nodejs_version: 8

matrix:
  fast_finish: true

cache:
  - node_modules/
  - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

before_test:
  - git config --global user.name 'CI'
  - git config --global user.email 'dummy@example.org'
  - npm install --global npm@latest
  - node --version
  - npm --version

test_script:
  - npm run test-windows
