environment:
  matrix:
    - nodejs_version: 6
    - nodejs_version: 8

matrix:
  fast_finish: true

build: off

cache:
  - node_modules/
  - '%APPDATA%\npm-cache'

init:
  - git config --global user.name 'CI'
  - git config --global user.email 'dummy@example.org'
  - npm install --global npm@latest
  - node --version
  - npm --version

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - npm run test-windows
