name: Node CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        os: [windows-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm test
      run: |
        npm install --global --update npm
        git config --global user.name 'CI'
        git config --global user.email 'dummy@example.org'
        npm ci
        npm test
      shell: bash
      env:
        CI: true
